### ISSUE TITLE
Appserver Link Broken

### ISSUE THREAD

**Issue by brandontamm** [DavidFeller/docker-appserver-magento#1]
Appserver tag missing from Docker Hub. "Latest" worked to pull repository, however, got some errors on docker-compose up:
web_1     |
web_1     | Warning: error_log(var/log/appserver-errors.log): failed to open stream: Permission denied in /opt/appserver/vendor/appserver-io/logger/src/AppserverIo/Logger/Handlers/CustomFileHandler.php on line 82
web_1     |
web_1     | Call Stack:
web_1     |     0.0293     240000   1. {main}() /opt/appserver/server.php:0
web_1     |     4.2101    2428184   2. AppserverIo\Appserver\Core\Server->start() /opt/appserver/server.php:285
web_1     |     5.2977    2444552   3. AppserverIo\Appserver\Core\Server->switchProcessUser() /opt/appserver/src/AppserverIo/Appserver/Core/Server.php:442
web_1     |     5.5309    2445856   4. AppserverIo\Logger\Logger->info() /opt/appserver/src/AppserverIo/Appserver/Core/Server.php:595
web_1     |     5.5309    2446072   5. AppserverIo\Logger\Logger->log() /opt/appserver/vendor/appserver-io/logger/src/AppserverIo/Logger/Logger.php:248
web_1     |     5.5310    2446768   6. AppserverIo\Logger\Logger->process() /opt/appserver/vendor/appserver-io/logger/src/AppserverIo/Logger/Logger.php:275
web_1     |     5.5310    2446768   7. AppserverIo\Logger\Handlers\CustomFileHandler->handle() /opt/appserver/vendor/appserver-io/logger/src/AppserverIo/Logger/Logger.php:296
web_1     |     5.5316    2447032   8. error_log() /opt/appserver/vendor/appserver-io/logger/src/AppserverIo/Logger/Handlers/CustomFileHandler.php:82
web_1     |
mysql_1   | 150921 18:44:08 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
web_1     |
web_1     | Warning: error_log(var/log/appserver-errors.log): failed to open stream: Permission denied in /opt/appserver/vendor/appserver-io/logger/src/AppserverIo/Logger/Handlers/CustomFileHandler.php on line 82
web_1     |
web_1     | Call Stack:
web_1     |     0.0293     240000   1. {main}() /opt/appserver/server.php:0
web_1     |     4.2101    2428184   2. AppserverIo\Appserver\Core\Server->start() /opt/appserver/server.php:285
web_1     |    28.2633    4338456   3. AppserverIo\Appserver\Core\Server->provision() /opt/appserver/src/AppserverIo/Appserver/Core/Server.php:451
web_1     |    29.5980    4453776   4. AppserverIo\Logger\Logger->info() /opt/appserver/src/AppserverIo/Appserver/Core/Server.php:635
web_1     |    29.5980    4453992   5. AppserverIo\Logger\Logger->log() /opt/appserver/vendor/appserver-io/logger/src/AppserverIo/Logger/Logger.php:248
web_1     |    29.5980    4454688   6. AppserverIo\Logger\Logger->process() /opt/appserver/vendor/appserver-io/logger/src/AppserverIo/Logger/Logger.php:275
web_1     |    29.5981    4454688   7. AppserverIo\Logger\Handlers\CustomFileHandler->handle() /opt/appserver/vendor/appserver-io/logger/src/AppserverIo/Logger/Logger.php:296
web_1     |    29.5984    4454960   8. error_log() /opt/appserver/vendor/appserver-io/logger/src/AppserverIo/Logger/Handlers/CustomFileHandler.php:82
web_1     |

**Comment by DavidFeller** [comment]
The appserver.io team now provides an official Dockerfile (https://github.com/appserver-io/appserver) for the current version 1.1.3.
