### ISSUE TITLE
ERROR: Tag 1.0.6 not found in repository docker.io/normvarianz/appserver

### ISSUE THREAD

**Issue by elephp7nt** [DavidFeller/docker-appserver-magento#2]
After running 'docker-compose up' it starts to install then throws the

ERROR: Tag 1.0.6 not found in repository docker.io/normvarianz/appserver
Thanks.

**Comment by DavidFeller** [comment]
The appserver.io team now provides an official Dockerfile (https://github.com/appserver-io/appserver) for the current version 1.1.3.
